name: Deploy Func

on:
  workflow_call:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AZURE_CLIENT_ID: ${{ vars.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ vars.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ vars.AZURE_SUBSCRIPTION_ID }}
      AZURE_ENV_NAME: ${{ vars.AZURE_ENV_NAME }}
      AZURE_LOCATION: ${{ vars.AZURE_LOCATION }}
      AZURE_APPSERVICEPLAN_NAME: ${{ vars.AZURE_APPSERVICEPLAN_NAME }}
      AZURE_APPSERVICEPLAN_RG: ${{ vars.AZURE_APPSERVICEPLAN_RG }}
      AZURE_KEYVAULT_NAME: ${{ vars.AZURE_KEYVAULT_NAME }}
      AZURE_KEYVAULT_RG: ${{ vars.AZURE_KEYVAULT_RG }}
    steps:
      - uses: actions/checkout@v4

      - name: Google 認証情報を配置
        uses: jsdaniell/create-json@v1.2.2
        with:
          name: "credentials.json"
          json: ${{ secrets.GOOGLE_CREDENTIALS }}
          dir: "src/func"

      - name: azd のセットアップ
        uses: Azure/setup-azd@v2

      - name: Azure へのログイン (OIDC)
        run: |
          azd auth login \
            --client-id "$AZURE_CLIENT_ID" \
            --federated-credential-provider "github" \
            --tenant-id "$AZURE_TENANT_ID"

      - name: Func をデプロイ
        uses: ./.github/actions/azd-service-deploy
        with:
          service_name: func
          service_path: src/func
